/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tudien2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.StringTokenizer;
import static javax.swing.JFrame.setDefaultLookAndFeelDecorated;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jvnet.substance.skin.SubstanceDustLookAndFeel;

/**
 *
 * @author PRO
 */
public class NewJFrame extends javax.swing.JFrame {

    String filenameE_V = "E-V.txt";
    String filenameV_E = "V-E.txt";
    BST treeEV = new BST();
    BST treeVE = new BST();
    
    
    public NewJFrame() {
        initComponents();
        loadData();
        Thread autoSave = new Thread() {
            @Override
            public void run() {
                try {
                    while (true) {
                        Thread.sleep(5000);
                        save();
                    }
                } catch (Exception e) {
                }
            }
        };
        autoSave.start();
    }
    
    public void loadEV(){
        try {
            FileReader f = new FileReader(filenameE_V);
            BufferedReader bf = new BufferedReader(f);
            String S;
            String s;
            String[] m = null;
            while ((S = bf.readLine())!=null){
                StringTokenizer stk = new StringTokenizer(S, ":");
                String word = stk.nextToken().trim();
                LinkedList ll = new LinkedList();
                m = stk.nextToken().trim().split(",");
                for(int i = 0; i <m.length; i++){
                    ll.addLast(m[i]);
                }
                BSTNode E = new BSTNode(word, ll);
                treeEV.Insert(E);
            }
            bf.close();
            f.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public void loadVE(){
        try {
            FileReader f = new FileReader(filenameV_E);
            BufferedReader bf = new BufferedReader(f);
            String S;
            String s;
            String[] m = null;
            while ((S = bf.readLine())!=null){
                StringTokenizer stk = new StringTokenizer(S, ":");
                String word = stk.nextToken().trim();
                LinkedList ll = new LinkedList();
                m = stk.nextToken().trim().split(",");
                for(int i = 0; i <m.length; i++){
                    ll.addLast(m[i]);
                }
                BSTNode E = new BSTNode(word, ll);
                treeVE.Insert(E);
            }
            bf.close();
            f.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void loadData(){
        loadEV();
        loadVE();
        rbte.setSelected(true);
    }
    
    public String getMeans(LinkedList means) {
        String result = "";
        for (int i = 0; i < means.size(); i++) {
            result = result + means.get(i);
            if (i < (means.size() - 1)) {
                result = result + ",";
            }
        }
        return result;
    }
    
    public void PreorderToPrint(BSTNode p, PrintWriter pw){
        if(p!=null){
            pw.println(p.toString());
            PreorderToPrint(p.left, pw);
            PreorderToPrint(p.right, pw);
        }
    }
    public void saveEV(){
        try {
            PrintWriter pw = new PrintWriter(filenameE_V);
            PreorderToPrint(treeEV.root, pw);
            pw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void saveVE() {
        try {
            PrintWriter pw = new PrintWriter(filenameV_E);
            PreorderToPrint(treeVE.root, pw);
            pw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void save() {
        saveEV();
        saveVE();
        Date d = new Date(System.currentTimeMillis());
        lblTime.setText("Data saved at: " + d.toString());
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtWord = new javax.swing.JTextField();
        txtMeans = new javax.swing.JTextField();
        rbte = new javax.swing.JRadioButton();
        rbtV = new javax.swing.JRadioButton();
        lblTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNewWord = new javax.swing.JTextField();
        txtNewMean = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dictionary ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setText("Word: ");

        jLabel2.setText("Means:");

        btnSearch.setText("Translate");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbte);
        rbte.setText("E-V dictionary ");

        buttonGroup1.add(rbtV);
        rbtV.setText("V-E dictionary ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbte)
                        .addGap(18, 18, 18)
                        .addComponent(rbtV)
                        .addGap(168, 168, 168)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 215, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtMeans)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtV)
                    .addComponent(rbte)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMeans, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtWord))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add new word"));

        jLabel3.setText("New Word: ");

        jLabel4.setText("New Means");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNewWord, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(txtNewMean))
                .addGap(47, 47, 47)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtNewWord, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewMean, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (rbte.isSelected() == true) {
            BSTNode find = treeEV.Search(txtWord.getText());
            if (find == null) {
                JOptionPane.showMessageDialog(this, "This word is not in the dictionary");
                txtMeans.setText("");
                txtWord.requestFocus();
            } else {
                txtMeans.setText(find.getMeans(find.means));
            }
        } else {
            BSTNode find = treeVE.Search(txtWord.getText());
            if (find == null) {
                JOptionPane.showMessageDialog(this, "This word is not in the dictionary");
                txtMeans.setText("");
                txtWord.requestFocus();
            } else {
                txtMeans.setText(find.getMeans(find.means));
            }
        }
        txtNewMean.setText("");
        txtNewWord.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    public void addNewWord(String word, String mean, BST tree) {
        int check = 0;
        BSTNode nn = tree.Search(word);
        if (nn == null) {
            LinkedList ll = new LinkedList();
            ll.add(mean);
            tree.Insert(new BSTNode(word, ll));
            JOptionPane.showMessageDialog(this, "Added new word!!!!");
        } else {
            int nnsize = nn.means.size();
            for (int i = 0; i < nn.means.size(); i++) {
                if (mean.equals(nn.means.get(i))) {
                    check++;
                }
            }
            if (check != 0) {
                JOptionPane.showMessageDialog(this, "The dictionary had this word");
            } else {
                nn.means.add(mean);
                JOptionPane.showMessageDialog(this, "Added new means!!!!");
            }
        }
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (rbte.isSelected() == true) {
            addNewWord(txtNewWord.getText(), txtNewMean.getText(), treeEV);
        } else {
            addNewWord(txtNewWord.getText(), txtNewMean.getText(), treeVE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
              setDefaultLookAndFeelDecorated(true);
              UIManager.setLookAndFeel(new SubstanceDustLookAndFeel());
//              UIManager.setLookAndFeel(new SubstanceSaharaLookAndFeel());
              
              
          }catch(Exception e){
              
          }
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JRadioButton rbtV;
    private javax.swing.JRadioButton rbte;
    private javax.swing.JTextField txtMeans;
    private javax.swing.JTextField txtNewMean;
    private javax.swing.JTextField txtNewWord;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
